global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - 192.168.3.190:9093  # Change your ip server

rule_files:
  - alert.rules.yml
  - alert.container.yml
  - alert.winserver.yml


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jira'
    scheme: https # change to http if don't you have https
    metrics_path: '/plugins/servlet/prometheus/metrics'
    params:
         token: ['KnhtPyxFKapM8qQr5hMC0G8c4oJ49We24lb']
    static_configs:
      - targets: ['it.hbc.com.vn'] # Jira host and port you serve        


  # Job for cadvisor  - IP Docker host
  #- job_name: 'DOCKER-PROMETHEUS-SERVER'
   # static_configs:
    #   - targets: ['192.168.3.11:8080']

  - job_name: 'DOCKER-99'
    static_configs:
       - targets: ['192.168.3.99:9200']




  # Job for node_exporter - server linux :9100, window:9182
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100' ]

  - job_name: 'Web-Cyberpanel-25'
    static_configs:
       - targets: ['115.79.26.177:9100']


  - job_name: 'HOST-DOCKER-99'
    static_configs:
       - targets: ['192.168.3.99:9100']

  - job_name: 'SAP DATABASE'
    static_configs:
       - targets: ['192.168.3.190:4000']

  - job_name: 'HOST-DOCKER-DMZ'
    static_configs:
       - targets: ['115.79.26.177:9101']

                
  - job_name: snmp
    scrape_interval: 5s
    static_configs:
      - targets:
          - "192.168.3.131"
    metrics_path: /snmp
    params:
      module: [apcups]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.3.190:9116 # địa chỉ IP của máy host

  - job_name: synology
    scrape_interval: 5s
    static_configs:
      - targets:
          - "172.16.10.239"
    metrics_path: /snmp
    params:
      module: [synology]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.3.190:9116 # địa chỉ IP của máy host
